### ISSUE TITLE
After Upgrade to 1.0.3 Error 500

### ISSUE THREAD

**Issue by ghost** [AndyRixon/LayerBB#22]
### Expected Behaviour

Hi Developers,

I have just upgraded to v1.0.3 but in the end there are 500 errors in the browser and the forum is no longer available.

Why is it because you made changes to Updater?

Can you help me somehow?

My LayerBB board is under https://layerbb.cms-blogger.eu and no longer available.

Thanks in advance.

### Steps to Reproduce Issue

Fresh Upgrade to v1.0.3

### Server Environment (PHP, MySQL, Apache Version and Operating System)

Ubuntu, Shared Hosting, PHP 7.1, MariaDB 10.1 with Redline

**Comment by KarlBrittain** [comment]
This is a simple fix. 

Within your file manager, go to applications > apps

Then rename 'WhatsHot' to whatshot. Taking off the capitals. 

This should fix the problem. We are aware of this and we are fixing this straight away.

**Comment by ghost** [comment]
Sorry, but unfortunately did not help and still 500 Error. What else could be the reason. I have already tried another PHP version.

WhatsHot is now "whatshot", but that does not help.

**Comment by AndyRixon** [comment]
This is not related to LayerBB itself, it is related to the WhatsHot application.
Please send me an email to info@layerbb.com with your FTP details and I will take a look. (I do not need control panel login information, JUST FTP)

**Comment by ghost** [comment]
Just sent you an email with the FTP login data.

**Comment by ghost** [comment]
I have uploaded v1.0.2 again and made an update. The forum is back.

**Comment by AndyRixon** [comment]
Hey Alex,

I have gone ahead and updated your forums, and followed the instructions that Karl told you. Karl however did forget to tell you to create an empty file called functions.php in 'applications/apps/whatshot/'.

All fixed for you now.

By the way, I tried replying to your email and it failed to send due to an issue with your mail server.

**For others trying to fix this issue, heres how;**

- Rename WhatsHot folder to whatshot within 'applications/apps'
- Create an empty file called 'functions.php' within 'applications/apps/whatshot/'

**Comment by ghost** [comment]
Hi Andy,

Big Thanks, that you could devote yourself to my cause so quickly. I appreciate very much. Good that we have now learned what had to be done to make the update.

I see in my forum now the version 1.0.3, which is very gratifying and thank you for the good support in this app 👍 

Presumably my mail server was not available for a short time, but I have already received numerous e-mails today.
